-- ════════════════════════════════════════════════════════════════════════════
-- FoodBall — seed players_catalog (curated, web-verified notable players for the
-- 48 live WC2026 teams) so the Golden Boot / Golden Glove / Best Young Player
-- pickers have options. Until a full squads sync exists, this is the catalog the
-- tournament-long player pickers read; award SETTLEMENT stays admin-entered.
--
-- Each player is tied to its team by FIFA code (NULL-safe: a player whose team
-- is absent still inserts with team = NULL). Idempotent via a synthetic, stable
-- api_player_id ('seed:<code>:<name-slug>') + ON CONFLICT DO NOTHING, so re-runs
-- and a later real squads sync (with real api_player_id values) won't collide.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.players_catalog (api_player_id, name, team, position)
select v.apid, v.name, t.id, nullif(v.position,'')
from (values
  ('seed:mex:santiago-gimenez','Santiago Giménez','MEX','FW'),
  ('seed:mex:raul-jimenez','Raúl Jiménez','MEX','FW'),
  ('seed:mex:raul-rangel','Raúl Rangel','MEX','GK'),
  ('seed:mex:gilberto-mora','Gilberto Mora','MEX','MF'),
  ('seed:mex:edson-alvarez','Edson Álvarez','MEX','MF'),
  ('seed:cze:patrik-schick','Patrik Schick','CZE','FW'),
  ('seed:cze:adam-hlozek','Adam Hložek','CZE','FW'),
  ('seed:cze:jindrich-stanek','Jindřich Staněk','CZE','GK'),
  ('seed:cze:pavel-sulc','Pavel Šulc','CZE','MF'),
  ('seed:rsa:lyle-foster','Lyle Foster','RSA','FW'),
  ('seed:rsa:iqraam-rayners','Iqraam Rayners','RSA','FW'),
  ('seed:rsa:ronwen-williams','Ronwen Williams','RSA','GK'),
  ('seed:rsa:relebohile-mofokeng','Relebohile Mofokeng','RSA','FW'),
  ('seed:kor:son-heung-min','Son Heung-min','KOR','FW'),
  ('seed:kor:oh-hyeon-gyu','Oh Hyeon-gyu','KOR','FW'),
  ('seed:kor:kim-seung-gyu','Kim Seung-gyu','KOR','GK'),
  ('seed:kor:bae-jun-ho','Bae Jun-ho','KOR','MF'),
  ('seed:kor:lee-kang-in','Lee Kang-in','KOR','MF'),
  ('seed:can:jonathan-david','Jonathan David','CAN','FW'),
  ('seed:can:cyle-larin','Cyle Larin','CAN','FW'),
  ('seed:can:alphonso-davies','Alphonso Davies','CAN','DF'),
  ('seed:can:maxime-crepeau','Maxime Crépeau','CAN','GK'),
  ('seed:can:luc-de-fougerolles','Luc de Fougerolles','CAN','DF'),
  ('seed:bih:edin-dzeko','Edin Džeko','BIH','FW'),
  ('seed:bih:ermedin-demirovic','Ermedin Demirović','BIH','FW'),
  ('seed:bih:nikola-vasilj','Nikola Vasilj','BIH','GK'),
  ('seed:bih:esmir-bajraktarevic','Esmir Bajraktarević','BIH','FW'),
  ('seed:qat:almoez-ali','Almoez Ali','QAT','FW'),
  ('seed:qat:akram-afif','Akram Afif','QAT','FW'),
  ('seed:qat:meshaal-barsham','Meshaal Barsham','QAT','GK'),
  ('seed:sui:breel-embolo','Breel Embolo','SUI','FW'),
  ('seed:sui:dan-ndoye','Dan Ndoye','SUI','FW'),
  ('seed:sui:gregor-kobel','Gregor Kobel','SUI','GK'),
  ('seed:sui:johan-manzambi','Johan Manzambi','SUI','MF'),
  ('seed:sui:granit-xhaka','Granit Xhaka','SUI','MF'),
  ('seed:bra:vinicius-junior','Vinícius Júnior','BRA','FW'),
  ('seed:bra:raphinha','Raphinha','BRA','FW'),
  ('seed:bra:alisson','Alisson','BRA','GK'),
  ('seed:bra:endrick','Endrick','BRA','FW'),
  ('seed:bra:neymar','Neymar','BRA','FW'),
  ('seed:hai:duckens-nazon','Duckens Nazon','HAI','FW'),
  ('seed:hai:frantzdy-pierrot','Frantzdy Pierrot','HAI','FW'),
  ('seed:hai:wilson-isidor','Wilson Isidor','HAI','FW'),
  ('seed:hai:johny-placide','Johny Placide','HAI','GK'),
  ('seed:hai:jean-ricner-bellegarde','Jean-Ricner Bellegarde','HAI','MF'),
  ('seed:mar:brahim-diaz','Brahim Díaz','MAR','FW'),
  ('seed:mar:achraf-hakimi','Achraf Hakimi','MAR','DF'),
  ('seed:mar:yassine-bounou','Yassine Bounou','MAR','GK'),
  ('seed:mar:bilal-el-khannouss','Bilal El Khannouss','MAR','MF'),
  ('seed:sco:che-adams','Che Adams','SCO','FW'),
  ('seed:sco:lawrence-shankland','Lawrence Shankland','SCO','FW'),
  ('seed:sco:angus-gunn','Angus Gunn','SCO','GK'),
  ('seed:sco:ben-doak','Ben Doak','SCO','FW'),
  ('seed:sco:scott-mctominay','Scott McTominay','SCO','MF'),
  ('seed:aus:mohamed-toure','Mohamed Touré','AUS','FW'),
  ('seed:aus:mitchell-duke','Mitchell Duke','AUS','FW'),
  ('seed:aus:mathew-ryan','Mathew Ryan','AUS','GK'),
  ('seed:aus:nestory-irankunda','Nestory Irankunda','AUS','FW'),
  ('seed:aus:cristian-volpato','Cristian Volpato','AUS','MF'),
  ('seed:par:antonio-sanabria','Antonio Sanabria','PAR','FW'),
  ('seed:par:miguel-almiron','Miguel Almirón','PAR','FW'),
  ('seed:par:orlando-gill','Orlando Gill','PAR','GK'),
  ('seed:par:julio-enciso','Julio Enciso','PAR','FW'),
  ('seed:par:diego-gomez','Diego Gómez','PAR','MF'),
  ('seed:tur:kenan-yldz','Kenan Yıldız','TUR','FW'),
  ('seed:tur:kerem-akturkoglu','Kerem Aktürkoğlu','TUR','FW'),
  ('seed:tur:ugurcan-cakr','Uğurcan Çakır','TUR','GK'),
  ('seed:tur:arda-guler','Arda Güler','TUR','MF'),
  ('seed:tur:can-uzun','Can Uzun','TUR','FW'),
  ('seed:tur:hakan-calhanoglu','Hakan Çalhanoğlu','TUR','MF'),
  ('seed:usa:folarin-balogun','Folarin Balogun','USA','FW'),
  ('seed:usa:ricardo-pepi','Ricardo Pepi','USA','FW'),
  ('seed:usa:matt-freese','Matt Freese','USA','GK'),
  ('seed:usa:christian-pulisic','Christian Pulisic','USA','FW'),
  ('seed:usa:giovanni-reyna','Giovanni Reyna','USA','MF'),
  ('seed:usa:alex-freeman','Alex Freeman','USA','DF'),
  ('seed:ger:florian-wirtz','Florian Wirtz','GER','MF'),
  ('seed:ger:kai-havertz','Kai Havertz','GER','FW'),
  ('seed:ger:nick-woltemade','Nick Woltemade','GER','FW'),
  ('seed:ger:manuel-neuer','Manuel Neuer','GER','GK'),
  ('seed:ger:jamal-musiala','Jamal Musiala','GER','MF'),
  ('seed:ger:leroy-sane','Leroy Sané','GER','FW'),
  ('seed:ecu:enner-valencia','Enner Valencia','ECU','FW'),
  ('seed:ecu:kevin-rodriguez','Kevin Rodríguez','ECU','FW'),
  ('seed:ecu:hernan-galindez','Hernán Galíndez','ECU','GK'),
  ('seed:ecu:kendry-paez','Kendry Páez','ECU','MF'),
  ('seed:ecu:moises-caicedo','Moisés Caicedo','ECU','MF'),
  ('seed:ecu:gonzalo-plata','Gonzalo Plata','ECU','FW'),
  ('seed:civ:evann-guessand','Evann Guessand','CIV','FW'),
  ('seed:civ:elye-wahi','Elye Wahi','CIV','FW'),
  ('seed:civ:yahia-fofana','Yahia Fofana','CIV','GK'),
  ('seed:civ:yan-diomande','Yan Diomandé','CIV','FW'),
  ('seed:civ:amad-diallo','Amad Diallo','CIV','FW'),
  ('seed:civ:simon-adingra','Simon Adingra','CIV','FW'),
  ('seed:cuw:jurgen-locadia','Jurgen Locadia','CUW','FW'),
  ('seed:cuw:gervane-kastaneer','Gervane Kastaneer','CUW','FW'),
  ('seed:cuw:eloy-room','Eloy Room','CUW','GK'),
  ('seed:cuw:tahith-chong','Tahith Chong','CUW','MF'),
  ('seed:cuw:leandro-bacuna','Leandro Bacuna','CUW','MF'),
  ('seed:jpn:ayase-ueda','Ayase Ueda','JPN','FW'),
  ('seed:jpn:daizen-maeda','Daizen Maeda','JPN','FW'),
  ('seed:jpn:zion-suzuki','Zion Suzuki','JPN','GK'),
  ('seed:jpn:keisuke-goto','Keisuke Gotō','JPN','FW'),
  ('seed:jpn:takefusa-kubo','Takefusa Kubo','JPN','MF'),
  ('seed:ned:memphis-depay','Memphis Depay','NED','FW'),
  ('seed:ned:cody-gakpo','Cody Gakpo','NED','FW'),
  ('seed:ned:bart-verbruggen','Bart Verbruggen','NED','GK'),
  ('seed:ned:jorrel-hato','Jorrel Hato','NED','DF'),
  ('seed:ned:virgil-van-dijk','Virgil van Dijk','NED','DF'),
  ('seed:swe:alexander-isak','Alexander Isak','SWE','FW'),
  ('seed:swe:viktor-gyokeres','Viktor Gyökeres','SWE','FW'),
  ('seed:swe:robin-olsen','Robin Olsen','SWE','GK'),
  ('seed:swe:lucas-bergvall','Lucas Bergvall','SWE','MF'),
  ('seed:swe:anthony-elanga','Anthony Elanga','SWE','FW'),
  ('seed:tun:hazem-mastouri','Hazem Mastouri','TUN','FW'),
  ('seed:tun:elias-achouri','Elias Achouri','TUN','FW'),
  ('seed:tun:aymen-dahmen','Aymen Dahmen','TUN','GK'),
  ('seed:tun:hannibal-mejbri','Hannibal Mejbri','TUN','MF'),
  ('seed:tun:ellyes-skhiri','Ellyes Skhiri','TUN','MF'),
  ('seed:bel:romelu-lukaku','Romelu Lukaku','BEL','FW'),
  ('seed:bel:jeremy-doku','Jérémy Doku','BEL','FW'),
  ('seed:bel:thibaut-courtois','Thibaut Courtois','BEL','GK'),
  ('seed:bel:kevin-de-bruyne','Kevin De Bruyne','BEL','MF'),
  ('seed:bel:matias-fernandez-pardo','Matías Fernández-Pardo','BEL','FW'),
  ('seed:egy:mohamed-salah','Mohamed Salah','EGY','FW'),
  ('seed:egy:mohamed-el-shenawy','Mohamed El Shenawy','EGY','GK'),
  ('seed:egy:omar-marmoush','Omar Marmoush','EGY','FW'),
  ('seed:egy:hamza-abdelkarim','Hamza Abdelkarim','EGY','FW'),
  ('seed:irn:mehdi-taremi','Mehdi Taremi','IRN','FW'),
  ('seed:irn:mohammad-mohebi','Mohammad Mohebi','IRN','MF'),
  ('seed:irn:alireza-beiranvand','Alireza Beiranvand','IRN','GK'),
  ('seed:irn:mehdi-ghayedi','Mehdi Ghayedi','IRN','FW'),
  ('seed:irn:amirmohammad-razzaghinia','Amirmohammad Razzaghinia','IRN','MF'),
  ('seed:nzl:chris-wood','Chris Wood','NZL','FW'),
  ('seed:nzl:max-crocombe','Max Crocombe','NZL','GK'),
  ('seed:nzl:tyler-bindon','Tyler Bindon','NZL','DF'),
  ('seed:nzl:marko-stamenic','Marko Stamenić','NZL','MF'),
  ('seed:nzl:sarpreet-singh','Sarpreet Singh','NZL','MF'),
  ('seed:esp:lamine-yamal','Lamine Yamal','ESP','FW'),
  ('seed:esp:nico-williams','Nico Williams','ESP','FW'),
  ('seed:esp:mikel-oyarzabal','Mikel Oyarzabal','ESP','FW'),
  ('seed:esp:unai-simon','Unai Simón','ESP','GK'),
  ('seed:esp:pedri','Pedri','ESP','MF'),
  ('seed:uru:darwin-nunez','Darwin Núñez','URU','FW'),
  ('seed:uru:federico-valverde','Federico Valverde','URU','MF'),
  ('seed:uru:sergio-rochet','Sergio Rochet','URU','GK'),
  ('seed:uru:luciano-rodriguez','Luciano Rodríguez','URU','FW'),
  ('seed:uru:ronald-araujo','Ronald Araújo','URU','DF'),
  ('seed:cpv:ryan-mendes','Ryan Mendes','CPV','FW'),
  ('seed:cpv:dailon-livramento','Dailon Livramento','CPV','FW'),
  ('seed:cpv:garry-rodrigues','Garry Rodrigues','CPV','FW'),
  ('seed:cpv:vozinha','Vozinha','CPV','GK'),
  ('seed:ksa:salem-al-dawsari','Salem Al-Dawsari','KSA','FW'),
  ('seed:ksa:firas-al-buraikan','Firas Al-Buraikan','KSA','FW'),
  ('seed:ksa:nawaf-al-aqidi','Nawaf Al-Aqidi','KSA','GK'),
  ('seed:ksa:musab-al-juwayr','Musab Al-Juwayr','KSA','MF'),
  ('seed:fra:kylian-mbappe','Kylian Mbappé','FRA','FW'),
  ('seed:fra:ousmane-dembele','Ousmane Dembélé','FRA','FW'),
  ('seed:fra:mike-maignan','Mike Maignan','FRA','GK'),
  ('seed:fra:desire-doue','Désiré Doué','FRA','MF'),
  ('seed:fra:michael-olise','Michael Olise','FRA','FW'),
  ('seed:nor:erling-haaland','Erling Haaland','NOR','FW'),
  ('seed:nor:alexander-srloth','Alexander Sørloth','NOR','FW'),
  ('seed:nor:rjan-nyland','Ørjan Nyland','NOR','GK'),
  ('seed:nor:antonio-nusa','Antonio Nusa','NOR','FW'),
  ('seed:nor:martin-degaard','Martin Ødegaard','NOR','MF'),
  ('seed:sen:nicolas-jackson','Nicolas Jackson','SEN','FW'),
  ('seed:sen:ismaila-sarr','Ismaïla Sarr','SEN','FW'),
  ('seed:sen:edouard-mendy','Édouard Mendy','SEN','GK'),
  ('seed:sen:lamine-camara','Lamine Camara','SEN','MF'),
  ('seed:sen:sadio-mane','Sadio Mané','SEN','FW'),
  ('seed:irq:aymen-hussein','Aymen Hussein','IRQ','FW'),
  ('seed:irq:ali-al-hamadi','Ali Al-Hamadi','IRQ','FW'),
  ('seed:irq:jalal-hassan','Jalal Hassan','IRQ','GK'),
  ('seed:irq:ali-jasim','Ali Jasim','IRQ','FW'),
  ('seed:irq:zidane-iqbal','Zidane Iqbal','IRQ','MF'),
  ('seed:arg:lautaro-martinez','Lautaro Martínez','ARG','FW'),
  ('seed:arg:julian-alvarez','Julián Álvarez','ARG','FW'),
  ('seed:arg:lionel-messi','Lionel Messi','ARG','FW'),
  ('seed:arg:emiliano-martinez','Emiliano Martínez','ARG','GK'),
  ('seed:arg:nico-paz','Nico Paz','ARG','MF'),
  ('seed:alg:mohamed-amine-amoura','Mohamed Amine Amoura','ALG','FW'),
  ('seed:alg:amine-gouiri','Amine Gouiri','ALG','FW'),
  ('seed:alg:riyad-mahrez','Riyad Mahrez','ALG','FW'),
  ('seed:alg:luca-zidane','Luca Zidane','ALG','GK'),
  ('seed:alg:ibrahim-maza','Ibrahim Maza','ALG','MF'),
  ('seed:aut:marko-arnautovic','Marko Arnautović','AUT','FW'),
  ('seed:aut:michael-gregoritsch','Michael Gregoritsch','AUT','FW'),
  ('seed:aut:david-alaba','David Alaba','AUT','DF'),
  ('seed:aut:alexander-schlager','Alexander Schlager','AUT','GK'),
  ('seed:aut:paul-wanner','Paul Wanner','AUT','MF'),
  ('seed:jor:ali-olwan','Ali Olwan','JOR','FW'),
  ('seed:jor:mousa-al-tamari','Mousa Al-Tamari','JOR','FW'),
  ('seed:jor:yazeed-abulaila','Yazeed Abulaila','JOR','GK'),
  ('seed:col:luis-diaz','Luis Díaz','COL','FW'),
  ('seed:col:jhon-cordoba','Jhon Córdoba','COL','FW'),
  ('seed:col:camilo-vargas','Camilo Vargas','COL','GK'),
  ('seed:col:gustavo-puerta','Gustavo Puerta','COL','MF'),
  ('seed:col:james-rodriguez','James Rodríguez','COL','MF'),
  ('seed:cod:yoane-wissa','Yoane Wissa','COD','FW'),
  ('seed:cod:cedric-bakambu','Cédric Bakambu','COD','FW'),
  ('seed:cod:lionel-mpasi','Lionel Mpasi','COD','GK'),
  ('seed:cod:matthieu-epolo','Matthieu Epolo','COD','GK'),
  ('seed:cod:chancel-mbemba','Chancel Mbemba','COD','DF'),
  ('seed:por:cristiano-ronaldo','Cristiano Ronaldo','POR','FW'),
  ('seed:por:goncalo-ramos','Gonçalo Ramos','POR','FW'),
  ('seed:por:diogo-costa','Diogo Costa','POR','GK'),
  ('seed:por:joao-neves','João Neves','POR','MF'),
  ('seed:por:rafael-leao','Rafael Leão','POR','FW'),
  ('seed:por:bruno-fernandes','Bruno Fernandes','POR','MF'),
  ('seed:por:vitinha','Vitinha','POR','MF'),
  ('seed:por:nuno-mendes','Nuno Mendes','POR','DF'),
  ('seed:uzb:eldor-shomurodov','Eldor Shomurodov','UZB','FW'),
  ('seed:uzb:utkir-yusupov','Utkir Yusupov','UZB','GK'),
  ('seed:uzb:abbosbek-fayzullaev','Abbosbek Fayzullaev','UZB','MF'),
  ('seed:uzb:abdukodir-khusanov','Abdukodir Khusanov','UZB','DF'),
  ('seed:cro:andrej-kramaric','Andrej Kramarić','CRO','FW'),
  ('seed:cro:ante-budimir','Ante Budimir','CRO','FW'),
  ('seed:cro:dominik-livakovic','Dominik Livaković','CRO','GK'),
  ('seed:cro:petar-sucic','Petar Sučić','CRO','MF'),
  ('seed:cro:luka-modric','Luka Modrić','CRO','MF'),
  ('seed:cro:josko-gvardiol','Joško Gvardiol','CRO','DF'),
  ('seed:eng:harry-kane','Harry Kane','ENG','FW'),
  ('seed:eng:bukayo-saka','Bukayo Saka','ENG','FW'),
  ('seed:eng:jordan-pickford','Jordan Pickford','ENG','GK'),
  ('seed:eng:jude-bellingham','Jude Bellingham','ENG','MF'),
  ('seed:eng:marcus-rashford','Marcus Rashford','ENG','FW'),
  ('seed:eng:ollie-watkins','Ollie Watkins','ENG','FW'),
  ('seed:gha:inaki-williams','Iñaki Williams','GHA','FW'),
  ('seed:gha:antoine-semenyo','Antoine Semenyo','GHA','FW'),
  ('seed:gha:lawrence-ati-zigi','Lawrence Ati-Zigi','GHA','GK'),
  ('seed:gha:ernest-nuamah','Ernest Nuamah','GHA','FW'),
  ('seed:gha:thomas-partey','Thomas Partey','GHA','MF'),
  ('seed:gha:jordan-ayew','Jordan Ayew','GHA','FW'),
  ('seed:pan:jose-fajardo','José Fajardo','PAN','FW'),
  ('seed:pan:cecilio-waterman','Cecilio Waterman','PAN','FW'),
  ('seed:pan:ismael-diaz','Ismael Díaz','PAN','FW'),
  ('seed:pan:orlando-mosquera','Orlando Mosquera','PAN','GK'),
  ('seed:pan:adalberto-carrasquilla','Adalberto Carrasquilla','PAN','MF')
) as v(apid, name, code, position)
left join public.teams t on t.fifa_code = v.code
on conflict (api_player_id) do nothing;
